import NavbarVendor from "@/components/NavbarVendor";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function VendorLayout({ children }) {
  return (
    <>
      <NavbarVendor />
      {children}
    </>
  );
}
